# Generated by Django 3.2.8 on 2021-10-18 19:24

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='الصورة الرئيسية الاولى')),
                ('image_2', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='الصورة الرئيسية الثانيه')),
                ('image_3', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='الصورة الرئيسية الثالثة')),
            ],
        ),
        migrations.CreateModel(
            name='PlatsSalu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stan', models.CharField(db_index=True, max_length=100, verbose_name='أسم المدينة ')),
                ('adress', models.CharField(db_index=True, max_length=100, verbose_name='العنوان ')),
                ('map_plats', models.CharField(db_index=True, max_length=100, verbose_name='رابط العنوان ')),
                ('datom', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='ساعة البداء')),
                ('end_time', models.TimeField(verbose_name='ساعة المغادرة')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='أسم المنتج ')),
                ('name_sv', models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج ')),
                ('name_en', models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج ')),
                ('name_tr', models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج ')),
                ('name_ar', models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج ')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('descrip', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('descrip_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('descrip_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('descrip_tr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('descrip_ar', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('pro_image', models.ImageField(blank=True, null=True, upload_to='Produkten/', verbose_name='صور')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='سعر المنتج')),
                ('Discountprice', models.DecimalField(decimal_places=0, default='0', max_digits=7, verbose_name='سعر عند وجود خصم')),
                ('created', models.DateTimeField(verbose_name='تاريخ الاضافة')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ الاضافة')),
                ('available', models.BooleanField(default=False, verbose_name='توصيه مسيقا')),
                ('special', models.BooleanField(default=False, verbose_name='خصم')),
                ('new', models.BooleanField(default=False, verbose_name='وجود في سياره التوزيع')),
            ],
        ),
        migrations.CreateModel(
            name='ProImag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='produktbild')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='produktnamn')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plat_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
