# Generated by Django 3.2.8 on 2021-10-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image_1', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='الصورة')),
            ],
        ),
    ]
